<?php
$dir = __DIR__ . '/database/migrations';
$files = scandir($dir);

$schemas = [
    'course_categories' => "\$table->id();\n            \$table->string('name');\n            \$table->string('slug')->unique();\n            \$table->string('icon')->nullable();\n            \$table->integer('order_position')->default(0);\n            \$table->enum('status', ['draft', 'published'])->default('draft');\n            \$table->timestamps();",
    'courses' => "\$table->id();\n            \$table->foreignId('category_id')->constrained('course_categories');\n            \$table->string('title');\n            \$table->string('slug')->unique();\n            \$table->text('short_description')->nullable();\n            \$table->longText('full_description')->nullable();\n            \$table->string('thumbnail')->nullable();\n            \$table->string('duration')->nullable();\n            \$table->string('mode')->nullable();\n            \$table->text('eligibility')->nullable();\n            \$table->string('fee')->nullable();\n            \$table->boolean('certification')->default(false);\n            \$table->boolean('placement_support')->default(false);\n            \$table->json('technologies')->nullable();\n            \$table->boolean('featured')->default(false);\n            \$table->enum('status', ['draft', 'published', 'archived'])->default('draft');\n            \$table->string('seo_title')->nullable();\n            \$table->text('seo_description')->nullable();\n            \$table->timestamps();",
    'course_modules' => "\$table->id();\n            \$table->foreignId('course_id')->constrained()->cascadeOnDelete();\n            \$table->string('title');\n            \$table->text('description')->nullable();\n            \$table->integer('order_position')->default(0);\n            \$table->timestamps();",
    'course_faqs' => "\$table->id();\n            \$table->foreignId('course_id')->constrained()->cascadeOnDelete();\n            \$table->string('question');\n            \$table->text('answer');\n            \$table->integer('order_position')->default(0);\n            \$table->timestamps();",
    'trainings' => "\$table->id();\n            \$table->foreignId('course_id')->nullable()->constrained()->nullOnDelete();\n            \$table->string('title');\n            \$table->string('slug')->unique();\n            \$table->enum('type', ['summer', 'winter', 'industrial', 'internship', 'corporate', 'workshop']);\n            \$table->date('start_date')->nullable();\n            \$table->date('end_date')->nullable();\n            \$table->string('duration')->nullable();\n            \$table->string('location')->nullable();\n            \$table->string('mode')->nullable();\n            \$table->string('trainer')->nullable();\n            \$table->integer('seats')->nullable();\n            \$table->longText('description')->nullable();\n            \$table->string('image')->nullable();\n            \$table->enum('registration_status', ['open', 'closed'])->default('open');\n            \$table->enum('status', ['draft', 'published', 'archived'])->default('draft');\n            \$table->timestamps();",
    'companies' => "\$table->id();\n            \$table->string('name');\n            \$table->string('logo')->nullable();\n            \$table->string('website')->nullable();\n            \$table->timestamps();",
    'students' => "\$table->id();\n            \$table->string('name');\n            \$table->string('photo')->nullable();\n            \$table->foreignId('course_id')->nullable()->constrained()->nullOnDelete();\n            \$table->timestamps();",
    'placements' => "\$table->id();\n            \$table->foreignId('student_id')->constrained()->cascadeOnDelete();\n            \$table->foreignId('company_id')->constrained()->cascadeOnDelete();\n            \$table->string('job_role');\n            \$table->string('package')->nullable();\n            \$table->string('batch')->nullable();\n            \$table->date('placement_date')->nullable();\n            \$table->text('testimonial')->nullable();\n            \$table->boolean('published')->default(false);\n            \$table->timestamps();",
    'gallery_albums' => "\$table->id();\n            \$table->string('title');\n            \$table->string('slug')->unique();\n            \$table->string('category')->nullable();\n            \$table->string('cover_image')->nullable();\n            \$table->date('event_date')->nullable();\n            \$table->text('description')->nullable();\n            \$table->enum('status', ['draft', 'published'])->default('draft');\n            \$table->timestamps();",
    'gallery_images' => "\$table->id();\n            \$table->foreignId('album_id')->constrained('gallery_albums')->cascadeOnDelete();\n            \$table->string('image_path');\n            \$table->string('caption')->nullable();\n            \$table->integer('order_position')->default(0);\n            \$table->timestamps();",
    'team_members' => "\$table->id();\n            \$table->string('name');\n            \$table->string('designation');\n            \$table->string('photo')->nullable();\n            \$table->text('bio')->nullable();\n            \$table->integer('order_position')->default(0);\n            \$table->enum('status', ['draft', 'published'])->default('draft');\n            \$table->timestamps();",
    'testimonials' => "\$table->id();\n            \$table->string('name');\n            \$table->string('photo')->nullable();\n            \$table->foreignId('course_id')->nullable()->constrained()->nullOnDelete();\n            \$table->text('message');\n            \$table->tinyInteger('rating')->default(5);\n            \$table->enum('status', ['draft', 'published'])->default('draft');\n            \$table->timestamps();",
    'branches' => "\$table->id();\n            \$table->string('name');\n            \$table->text('address');\n            \$table->string('phone')->nullable();\n            \$table->string('email')->nullable();\n            \$table->text('map_embed')->nullable();\n            \$table->enum('status', ['draft', 'published'])->default('draft');\n            \$table->timestamps();",
    'enquiries' => "\$table->id();\n            \$table->string('name');\n            \$table->string('email')->nullable();\n            \$table->string('phone');\n            \$table->foreignId('course_id')->nullable()->constrained()->nullOnDelete();\n            \$table->text('message')->nullable();\n            \$table->enum('status', ['new', 'contacted', 'converted', 'closed'])->default('new');\n            \$table->timestamps();",
    'pages' => "\$table->id();\n            \$table->string('page_key')->unique();\n            \$table->string('title');\n            \$table->timestamps();",
    'page_sections' => "\$table->id();\n            \$table->foreignId('page_id')->constrained()->cascadeOnDelete();\n            \$table->string('section_key');\n            \$table->string('heading')->nullable();\n            \$table->longText('content')->nullable();\n            \$table->string('image')->nullable();\n            \$table->integer('order_position')->default(0);\n            \$table->timestamps();",
    'site_settings' => "\$table->id();\n            \$table->string('setting_key')->unique();\n            \$table->text('setting_value')->nullable();\n            \$table->timestamps();",
    'media' => "\$table->id();\n            \$table->string('file_path');\n            \$table->string('file_name');\n            \$table->string('mime_type')->nullable();\n            \$table->integer('size')->nullable();\n            \$table->timestamps();"
];

foreach ($files as $file) {
    if (str_ends_with($file, '.php')) {
        foreach ($schemas as $table => $schema) {
            if (str_contains($file, 'create_' . $table . '_table')) {
                $content = file_get_contents($dir . '/' . $file);
                $pattern = "/Schema::create\('$table', function \(Blueprint \\\$table\) \{(.*?)\}\);/s";
                $replacement = "Schema::create('$table', function (Blueprint \$table) {\n            $schema\n        });";
                $newContent = preg_replace($pattern, $replacement, $content);
                file_put_contents($dir . '/' . $file, $newContent);
                echo "Updated $file\n";
            }
        }
    }
}
